---
#- name: Обновление репозитория
#  shell: "apt update"

- name: Установка curl и ca-certificates
  apt: "name={{ item }} state=present"
  with_items:
    - ca-certificates
    - curl

- name: Скачивание ключа gpg для docker
  shell: |
    mkdir -p /etc/apt/keyrings && chmod 755 /etc/apt/keyrings &&
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc &&
    chmod a+r /etc/apt/keyrings/docker.asc &&
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
    apt update

- name: Установка Docker
  apt: "name={{ item }} state=present"
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin


