services:
  vuln_web:
    image: vulnerables/web-dvwa:latest
    container_name: WEB
    ports:
      - "8080:80"
    networks:
      - app-net

  nginx_proxy:
    build: .
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - app-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_log:/var/log/nginx/

  psql:
    image: postgres:latest
    container_name: DB
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglog:/var/log/postgresql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

networks:
  app-net:
