---
- name: Скачивание Node exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp
    mode: 755

- name: Разархивирование tar
  shell: "cd /tmp && tar xvf node_exporter-1.7.0.linux-amd64.tar.gz && cd node_exporter-1.7.0.linux-amd64 && mv node_exporter /usr/bin/"

- name: Создание пользователя node_exporter
  shell: "useradd -rs /bin/false node_exporter"

- name: Настройка прав
  shell: "chown node_exporter:node_exporter /usr/bin/node_exporter"

- name: Копирование конфига, для запуска Node exporter как службы
  copy: "src={{ item }} dest={{ systemd_path }}/node_exporter.service"
  with_items:
    - node_exporter.service

- name: Запуск службы
  shell: |
    systemctl daemon-reload &&
    systemctl start node_exporter &&
    systemctl enable node_exporter


