---
- name: Развертывание приложения через docker compose
  hosts: server
  become: yes
  roles:
     - docker_install
     - app_deploy
     - log_rot

- name: Развертывание мониторинга
  hosts: server
  become: yes
  roles:
    - prometheus_deploy
    - node_exporter_deploy
    - nginx_exporter_deploy
    - grafana_deploy

